# Generated by Django 6.1.1 on 2026-09-11 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='atencion.turno'),
        ),
    ]
