# Generated by Django 6.1.1 on 2026-09-06 23:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje_cobertura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tope_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio_cubierto', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dueno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dueno',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atencion.obrasocial'),
        ),
    ]
